
import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author beamj
 */
public class CustomThemeChooser extends javax.swing.JPanel {

    private Color main;
    private Color sub;
    
    /**
     * Creates new form CustomThemeChooser
     * @param m
     * @param s
     */
    public CustomThemeChooser(Color m, Color s) {
        main = m;
        sub = s;
        initComponents();
    }
    
    public ColorTheme getTheme(){
        return new ColorTheme(main, sub);
    }
    
    public CustomThemeChooser() {
        main = new Color(255, 255, 255);
        sub = new Color(255, 255, 255);
        initComponents();
    }

    public Color getMain() {
        return main;
    }

    public Color getSub() {
        return sub;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorPanel = new javax.swing.JPanel();
        mainColorButton = new javax.swing.JButton();
        subColorButton = new javax.swing.JButton();

        colorPanel.setLayout(new java.awt.GridLayout(2, 0));

        mainColorButton.setText("Choose Main Color!");
        mainColorButton.setToolTipText("Click this to choose your custom theme's main color!");
        mainColorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainColorButtonMouseClicked(evt);
            }
        });
        colorPanel.add(mainColorButton);

        subColorButton.setText("Choose Secondary Color!");
        subColorButton.setToolTipText("Click this to choose your custom theme's secondary color!");
        subColorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subColorButtonMouseClicked(evt);
            }
        });
        colorPanel.add(subColorButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mainColorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainColorButtonMouseClicked
        JColorChooser chooser = new JColorChooser(main);
        JOptionPane.showMessageDialog(this, chooser, "Choose Main Color!", JOptionPane.PLAIN_MESSAGE);
        main = chooser.getColor();
    }//GEN-LAST:event_mainColorButtonMouseClicked

    private void subColorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subColorButtonMouseClicked
        JColorChooser chooser = new JColorChooser(sub);
        JOptionPane.showMessageDialog(this, chooser, "Choose Secondary Color!", JOptionPane.PLAIN_MESSAGE);
        sub = chooser.getColor();
    }//GEN-LAST:event_subColorButtonMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel colorPanel;
    private javax.swing.JButton mainColorButton;
    private javax.swing.JButton subColorButton;
    // End of variables declaration//GEN-END:variables
}
