/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author beamj
 */
public class EditTimer extends javax.swing.JPanel {

    /**
     * Creates new form EditTimer
     * @param time
     */
    public EditTimer(Time  time) {
        initComponents();
        hourBox.setSelectedIndex(time.getHour());
        minuteBox.setSelectedIndex(time.getMinutes());
        secondBox.setSelectedIndex(time.getSeconds());
    }
    
    public Time getTime(){
        return new Time(hourBox.getSelectedIndex(), minuteBox.getSelectedIndex(), secondBox.getSelectedIndex());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeChooserPanel = new javax.swing.JPanel();
        hourLabel = new javax.swing.JLabel();
        minuteLabel = new javax.swing.JLabel();
        secondLabel = new javax.swing.JLabel();
        hourBox = new javax.swing.JComboBox<>();
        minuteBox = new javax.swing.JComboBox<>();
        secondBox = new javax.swing.JComboBox<>();

        timeChooserPanel.setToolTipText("Choose the time interval between each declaration.");
        timeChooserPanel.setLayout(new java.awt.GridLayout(2, 3));

        hourLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hourLabel.setText("Hours");
        timeChooserPanel.add(hourLabel);

        minuteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minuteLabel.setText("Minutes");
        timeChooserPanel.add(minuteLabel);

        secondLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondLabel.setText("Seconds");
        timeChooserPanel.add(secondLabel);

        hourBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        timeChooserPanel.add(hourBox);

        minuteBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        timeChooserPanel.add(minuteBox);

        secondBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        timeChooserPanel.add(secondBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(timeChooserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(timeChooserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> hourBox;
    private javax.swing.JLabel hourLabel;
    private javax.swing.JComboBox<String> minuteBox;
    private javax.swing.JLabel minuteLabel;
    private javax.swing.JComboBox<String> secondBox;
    private javax.swing.JLabel secondLabel;
    private javax.swing.JPanel timeChooserPanel;
    // End of variables declaration//GEN-END:variables
}
